"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import { useAuthStore } from "@/stores/authStore";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, PenTool, Mail, FileText, Copy } from "lucide-react";
import type { Draft } from "@/lib/types";

export default function DraftsPage() {
  const router = useRouter();
  const params = useParams();
  const caseId = params.id as string;
  const { user, isLoading, loadFromStorage } = useAuthStore();
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [expanded, setExpanded] = useState<string | null>(null);

  useEffect(() => { loadFromStorage(); }, [loadFromStorage]);

  useEffect(() => {
    if (user && caseId) {
      api.listDrafts(caseId).then((r) => setDrafts(r as unknown as Draft[]));
    }
  }, [user, caseId]);

  if (isLoading || !user) return null;

  const typeIcons: Record<string, typeof Mail> = {
    email: Mail,
    letter: FileText,
    complaint: FileText,
    memo: FileText,
    question: FileText,
  };

  const toneColors: Record<string, string> = {
    professional: "bg-blue-100 text-blue-700",
    firm: "bg-orange-100 text-orange-700",
    conciliatory: "bg-green-100 text-green-700",
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b bg-white">
        <div className="mx-auto flex max-w-4xl items-center gap-3 px-6 py-4">
          <Button variant="ghost" size="sm" onClick={() => router.push(`/cases/${caseId}`)}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <h1 className="text-lg font-semibold">Draft Studio</h1>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-8">
        <div className="mb-4 rounded-lg border border-blue-200 bg-blue-50 p-3">
          <p className="text-sm text-blue-800">
            Drafts are generated by the Draft Studio agent during your chat. Ask the Navigator to
            &quot;draft an email to the club&quot; or &quot;write a complaint letter&quot; to generate new drafts.
          </p>
        </div>

        {drafts.length === 0 ? (
          <Card>
            <CardContent className="flex flex-col items-center py-12">
              <PenTool className="mb-3 h-10 w-10 text-muted-foreground" />
              <p className="mb-1 font-medium">No drafts yet</p>
              <p className="text-sm text-muted-foreground">
                Ask the Navigator to draft communications for you.
              </p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-3">
            {drafts.map((draft) => {
              const Icon = typeIcons[draft.draft_type] || FileText;
              const isExpanded = expanded === draft.id;

              return (
                <Card key={draft.id}>
                  <CardContent className="p-4">
                    <div
                      className="flex cursor-pointer items-start justify-between"
                      onClick={() => setExpanded(isExpanded ? null : draft.id)}
                    >
                      <div className="flex items-start gap-3">
                        <Icon className="mt-0.5 h-5 w-5 text-muted-foreground" />
                        <div>
                          <h3 className="font-medium">{draft.title}</h3>
                          <div className="mt-1 flex items-center gap-2">
                            <Badge variant="outline" className="text-xs">{draft.draft_type}</Badge>
                            <Badge className={`text-xs ${toneColors[draft.tone] || ""}`}>
                              {draft.tone}
                            </Badge>
                            {draft.recipient && (
                              <span className="text-xs text-muted-foreground">
                                To: {draft.recipient}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        {new Date(draft.created_at).toLocaleDateString()}
                      </p>
                    </div>

                    {isExpanded && (
                      <div className="mt-4 rounded-lg bg-gray-50 p-4">
                        <div className="mb-2 flex justify-end">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => navigator.clipboard.writeText(draft.content)}
                          >
                            <Copy className="mr-1 h-3 w-3" /> Copy
                          </Button>
                        </div>
                        <div className="whitespace-pre-wrap text-sm">{draft.content}</div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}
